sudo: true
dist: trusty


language: python
python:
  - 2.7
  
notifications: 
  email: true
  slack: ${SLACK_TOKEN}
    on_success: always # default: change 
    on_failure: always # default: always  

notifications: 
  email: true
  slack:
    rooms:
      - ${SLACK_TOKEN}
    on_success: change # default: always
    on_failure: always # default: always  
